export const products = [
    {
        id: 1,
        name: "Premium Leather Jacket",
        price: 85000,
        salePrice: 69999,
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop",
        categories: ["men", "clothing"],
        subCategory: "outerwear",
        colors: ["black", "brown"],
        sizes: ["S", "M", "L", "XL"],
        isNew: true,
        description: "Hand-crafted from Italian leather, this jacket features a timeless design that only gets better with age. Features durable zippers and a comfortable lining.",
    },
    {
        id: 2,
        name: "Minimalist Gold Watch",
        price: 55999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=1000&auto=format&fit=crop",
        categories: ["accessories", "women"],
        subCategory: "watches",
        colors: ["gold", "silver"],
        sizes: ["One Size"],
        isNew: false,
        description: "A sleek and elegant timepiece for the modern professional. Water-resistant up to 50m with a scratch-resistant sapphire crystal face.",
    },
    {
        id: 3,
        name: "Urban Streetwear Hoodie",
        price: 24999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop",
        categories: ["men", "clothing"],
        subCategory: "hoodies",
        colors: ["black", "gray", "navy"],
        sizes: ["M", "L", "XL"],
        isNew: false,
        description: "Comfort meets style in this oversized premium cotton hoodie. Perfect for a casual day out or lounging at home.",
    },
    {
        id: 4,
        name: "Designer Sunglasses",
        price: 44999,
        salePrice: 36999,
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop",
        categories: ["accessories", "unisex"],
        subCategory: "eyewear",
        colors: ["black", "tortoise"],
        sizes: ["One Size"],
        isNew: true,
        description: "UV400 protection with polarized lenses. These designer frames offer both protection and a bold fashion statement.",
    },
    {
        id: 5,
        name: "Classic Denim Jeans",
        price: 22999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?q=80&w=1000&auto=format&fit=crop",
        categories: ["men", "clothing"],
        subCategory: "jeans",
        colors: ["blue", "black"],
        sizes: ["30", "32", "34", "36"],
        isNew: false,
        description: "Rugged and durable denim that fits perfectly. Stone-washed for that lived-in feel right from the first wear.",
    },
    {
        id: 6,
        name: "Silk Scarf",
        price: 12999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1584030373081-f37b7bb4fa1e?q=80&w=1000&auto=format&fit=crop",
        categories: ["women", "accessories"],
        subCategory: "scarves",
        colors: ["red", "blue", "multi"],
        sizes: ["One Size"],
        isNew: true,
        description: "100% pure silk scarf with a vibrant floral pattern. Adds a touch of luxury to any outfit.",
    },
    {
        id: 7,
        name: "Canvas Sneakers",
        price: 16999,
        salePrice: 13999,
        image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop",
        categories: ["unisex", "footwear"],
        subCategory: "sneakers",
        colors: ["white", "black", "red"],
        sizes: ["7", "8", "9", "10", "11"],
        isNew: false,
        description: "Lightweight and breathable canvas sneakers. The responsive sole ensures all-day comfort.",
    },
    {
        id: 8,
        name: "Leather Satchel",
        price: 52999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1000&auto=format&fit=crop",
        categories: ["women", "accessories"],
        subCategory: "bags",
        colors: ["brown", "tan"],
        sizes: ["One Size"],
        isNew: false,
        description: "Spacious enough for a laptop and daily essentials. Features adjustable straps and multiple compartments.",
    },
    {
        id: 9,
        name: "Wireless Earbuds Pro",
        price: 34999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop",
        categories: ["accessories", "unisex"],
        subCategory: "electronics",
        colors: ["black", "white"],
        sizes: ["One Size"],
        isNew: true,
        description: "Premium sound quality with active noise cancellation. 24-hour battery life and wireless charging case included.",
    },
    {
        id: 10,
        name: "Yoga Mat Premium",
        price: 8999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=1000&auto=format&fit=crop",
        categories: ["unisex", "accessories"],
        subCategory: "fitness",
        colors: ["purple", "blue", "pink"],
        sizes: ["One Size"],
        isNew: true,
        description: "Extra-thick non-slip yoga mat with carrying strap. Perfect for yoga, pilates, and floor exercises.",
    },
    {
        id: 11,
        name: "Smart Backpack",
        price: 29999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop",
        categories: ["unisex", "accessories"],
        subCategory: "bags",
        colors: ["black", "gray"],
        sizes: ["One Size"],
        isNew: true,
        description: "Water-resistant backpack with USB charging port and laptop compartment. Perfect for work and travel.",
    },
    {
        id: 12,
        name: "Running Shoes",
        price: 18999,
        salePrice: 15999,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
        categories: ["unisex", "footwear"],
        subCategory: "sneakers",
        colors: ["black", "blue", "red"],
        sizes: ["7", "8", "9", "10", "11"],
        isNew: true,
        description: "Lightweight running shoes with responsive cushioning and breathable mesh upper. Ideal for daily runs.",
    },
    {
        id: 13,
        name: "Ceramic Mug Set",
        price: 6999,
        salePrice: null,
        image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?q=80&w=1000&auto=format&fit=crop",
        categories: ["accessories", "unisex"],
        subCategory: "home",
        colors: ["white", "black", "multi"],
        sizes: ["One Size"],
        isNew: true,
        description: "Set of 4 handcrafted ceramic mugs with unique designs. Microwave and dishwasher safe.",
    },
];

export const categories = [
    {
        name: "Women",
        value: "women",
        image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=1000&auto=format&fit=crop",
        subCategories: ["clothing", "accessories", "footwear", "bags"]
    },
    {
        name: "Men",
        value: "men",
        image: "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?q=80&w=1000&auto=format&fit=crop",
        subCategories: ["clothing", "accessories", "footwear", "outerwear"]
    },
    {
        name: "Accessories",
        value: "accessories",
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d60f?q=80&w=1000&auto=format&fit=crop",
        subCategories: ["watches", "eyewear", "bags", "scarves"]
    },
];

export const colors = [
    { name: "Black", value: "black", class: "bg-black" },
    { name: "White", value: "white", class: "bg-white ring-1 ring-gray-200" },
    { name: "Gray", value: "gray", class: "bg-gray-500" },
    { name: "Blue", value: "blue", class: "bg-blue-600" },
    { name: "Red", value: "red", class: "bg-red-600" },
    { name: "Brown", value: "brown", class: "bg-amber-800" },
];

export const sizes = ["XS", "S", "M", "L", "XL", "XXL", "One Size", "7", "8", "9", "10", "11"];
